# Generated by Django 3.0.5 on 2020-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20200410_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language1',
            field=models.CharField(max_length=255, verbose_name='First Language'),
        ),
    ]
